defaults: &defaults
  
  app_name: Osc
  
  alive_sessions: 1 #minutes
  
  server:
    host: tcp://127.0.0.1
    port: 8080
  monitor:
    host: tcp://127.0.0.1
    port: 9234
  adapter:
    type: redis
    host: 127.0.0.1
    port: 6379

  pusher:
    app_id: "xxx"
    key: "xxx"
    secret: "xxx"

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults