defaults: &defaults
    
  server:
    host: tcp://127.0.0.1
    port: 8080
    nodes:
      one:
        port: 8080
      two:
        port: 8082
  monitor:
    host: tcp://127.0.0.1
    port: 9234
  adapter:
    type: redis
    host: 127.0.0.1
    port: 6379
    
  nodes: 3
    

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults